// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpeakerAPI.Data;

namespace SpeakerAPI.Data.Migrations
{
    [DbContext(typeof(SpeakerDbContext))]
    [Migration("20211126061433_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SpeakerLibrary.Speaker", b =>
                {
                    b.Property<string>("SpeakerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpeakerId");

                    b.ToTable("Speakers");

                    b.HasData(
                        new
                        {
                            SpeakerId = "3c008559-c39f-4854-af5e-6a46a88a151d",
                            City = "Burnaby",
                            Email = "tom@day.com",
                            Employer = "Tinder",
                            FirstName = "Tom",
                            LastName = "Day",
                            Mobile = "6041111111",
                            Province = "BC",
                            Specialization = "Love"
                        },
                        new
                        {
                            SpeakerId = "e338154c-ea64-490a-87ad-69bea86fe777",
                            City = "Langley",
                            Email = "ann@fox.com",
                            Employer = "Hunter",
                            FirstName = "Ann",
                            LastName = "Fox",
                            Mobile = "6042222222",
                            Province = "BC",
                            Specialization = "Hunting"
                        },
                        new
                        {
                            SpeakerId = "9d424e1e-4f86-4f9a-a0e9-569a473a5166",
                            City = "Vancouver",
                            Email = "art@ash.com",
                            Employer = "Art Gallery",
                            FirstName = "Art",
                            LastName = "Ash",
                            Mobile = "6043333333",
                            Province = "BC",
                            Specialization = "Art"
                        },
                        new
                        {
                            SpeakerId = "3d9289cb-21f3-48cc-ad98-af6dc55ba974",
                            City = "Coquitlam",
                            Email = "mia@hay.com",
                            Employer = "Hayers",
                            FirstName = "Mia",
                            LastName = "Hay",
                            Mobile = "6044444444",
                            Province = "BC",
                            Specialization = "Farmer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
