// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpeakerAPI.Data;

namespace SpeakerAPI.Data.Migrations
{
    [DbContext(typeof(SpeakerDbContext))]
    partial class SpeakerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SpeakerLibrary.Speaker", b =>
                {
                    b.Property<string>("SpeakerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpeakerId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            SpeakerId = "eb775c74-8314-4ae2-a7ce-af1cc91f87b6",
                            City = "Burnaby",
                            Email = "tom@day.com",
                            Employer = "Tinder",
                            FirstName = "Tom",
                            LastName = "Day",
                            Mobile = "6041111111",
                            Province = "BC",
                            Specialization = "Love"
                        },
                        new
                        {
                            SpeakerId = "3892da4a-c809-4580-8ab0-1cc4e0c99756",
                            City = "Langley",
                            Email = "ann@fox.com",
                            Employer = "Hunter",
                            FirstName = "Ann",
                            LastName = "Fox",
                            Mobile = "6042222222",
                            Province = "BC",
                            Specialization = "Hunting"
                        },
                        new
                        {
                            SpeakerId = "9f8ed802-42ce-46fe-944a-897a1f1360d0",
                            City = "Vancouver",
                            Email = "art@ash.com",
                            Employer = "Art Gallery",
                            FirstName = "Art",
                            LastName = "Ash",
                            Mobile = "6043333333",
                            Province = "BC",
                            Specialization = "Art"
                        },
                        new
                        {
                            SpeakerId = "b73f1fc6-b918-4767-8fdf-dee8013a8612",
                            City = "Coquitlam",
                            Email = "mia@hay.com",
                            Employer = "Hayers",
                            FirstName = "Mia",
                            LastName = "Hay",
                            Mobile = "6044444444",
                            Province = "BC",
                            Specialization = "Farmer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
