version: "3.4"
services:
  db:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SqlExpress!"

  webapi:
    build:
      context: .
      dockerfile: SpeakerAPI/Dockerfile
    restart: always
    environment:
      - DBHOST=db
      - DBPORT=1433
      - DBUSER=sa
      - DBNAME=Speaker
      - DBPASSWORD=SqlExpress!
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    ports:
      - "5000:80"
      - "5001:443"

  wasm:
    build:
      context: .
      dockerfile: BlazorClient/Dockerfile
    depends_on:
      - webapi
    ports:
      - 8888:80
